class CreateMeasurements < ActiveRecord::Migration
  def up
    create_table :measurements do |t|
      t.references :measure, index: true
      t.string :link
      t.references :document, index: true
      t.integer :year
      t.string :value

      t.timestamps
    end

    measures = {}
    Measure.all.each{ |m| measures[m.description] = m.id }

    Measurement.create! [
      { measure_id: measures['Juvenile law violations (rate per 1000)'], year: 2006, value: '71.6' },
      { measure_id: measures['Juvenile law violations (rate per 1000)'], year: 2009, value: '75.6' },
      { measure_id: measures['Juvenile cases filed'], year: 2006, value: '396' },
      { measure_id: measures['Juvenile cases filed'], year: 2007, value: '218' },
      { measure_id: measures['Juvenile cases filed'], year: 2008, value: '195' },
      { measure_id: measures['Juvenile cases filed'], year: 2009, value: '230' },
      { measure_id: measures['Juvenile cases filed'], year: 2010, value: '256' },
      { measure_id: measures['Juvenile cases filed'], year: 2011, value: '423' },
      { measure_id: measures['Juvenile cases filed'], year: 2012, value: '451' },
      { measure_id: measures['Youth who have ever used alcohol'], year: 2006, value: '53%' },
      { measure_id: measures['Youth who have ever used alcohol'], year: 2008, value: '52%' },
      { measure_id: measures['Youth who have ever used alcohol'], year: 2010, value: '40%' },
      { measure_id: measures['Youth who have ever used alcohol'], year: 2012, value: '32%' },
      { measure_id: measures['Youth past 30 days use of alcohol - by grade and in total'], year: 2006, value: '23%' },
      { measure_id: measures['Youth past 30 days use of alcohol - by grade and in total'], year: 2008, value: '26%' },
      { measure_id: measures['Youth past 30 days use of alcohol - by grade and in total'], year: 2010, value: '18%' },
      { measure_id: measures['Youth past 30 days use of alcohol - by grade and in total'], year: 2012, value: '12%' },
      { measure_id: measures['Youth who believe there is risk/harm to using alcohol - by grade and in total'], year: 2006, value: '68%' },
      { measure_id: measures['Youth who believe there is risk/harm to using alcohol - by grade and in total'], year: 2008, value: '68%' },
      { measure_id: measures['Youth who believe there is risk/harm to using alcohol - by grade and in total'], year: 2010, value: '79%' },
      { measure_id: measures['Youth who believe there is risk/harm to using alcohol - by grade and in total'], year: 2012, value: '75%' },
      { measure_id: measures['Youth who perceive parental disapproval of use of alcohol - by grade and in total'], year: 2006, value: '89%' },
      { measure_id: measures['Youth who perceive parental disapproval of use of alcohol - by grade and in total'], year: 2008, value: '87%' },
      { measure_id: measures['Youth who perceive parental disapproval of use of alcohol - by grade and in total'], year: 2010, value: '82%' },
      { measure_id: measures['Youth who perceive parental disapproval of use of alcohol - by grade and in total'], year: 2012, value: '87%' },
      { measure_id: measures['If one of your best friends offered you alcohol to drink, would you drink it - by grade and in total'], year: 2010, value: '26%' },
      { measure_id: measures['How wrong do you feel it would be for you to have a drink of any type of alcohol - by grade and in total'], year: 2006, value: '76%' },
      { measure_id: measures['How wrong do you feel it would be for you to have a drink of any type of alcohol - by grade and in total'], year: 2008, value: '74%' },
      { measure_id: measures['How wrong do you feel it would be for you to have a drink of any type of alcohol - by grade and in total'], year: 2010, value: '63%' },
      { measure_id: measures['How wrong do you feel it would be for you to have a drink of any type of alcohol - by grade and in total'], year: 2012, value: '71%' },
      { measure_id: measures['If you wanted to get some alcohol how easy would it be for you to get some? - by grade and in total'], year: 2006, value: '44%' },
      { measure_id: measures['If you wanted to get some alcohol how easy would it be for you to get some? - by grade and in total'], year: 2008, value: '46%' },
      { measure_id: measures['If you wanted to get some alcohol how easy would it be for you to get some? - by grade and in total'], year: 2010, value: '53%' },
      { measure_id: measures['If you wanted to get some alcohol how easy would it be for you to get some? - by grade and in total'], year: 2012, value: '46%' },
      { measure_id: measures['Number of compliance checks performed'], year: 2010, value: '210' },
      { measure_id: measures['Compliance rates of retailers selling to minors'], year: 2007, value: '0.56' },
      { measure_id: measures['Compliance rates of retailers selling to minors'], year: 2011, value: '0.2' },
      { measure_id: measures['Number of arrests for minors in possession - <= 17'], year: 2008, value: '62' },
      { measure_id: measures['Number of arrests for minors in possession - <= 17'], year: 2009, value: '59' },
      { measure_id: measures['Number of arrests for minors in possession - <= 17'], year: 2010, value: '46' },
      { measure_id: measures['Number of arrests for minors in possession - <= 17'], year: 2011, value: '45' },
      { measure_id: measures['Number of arrests for minors in possession - <= 17'], year: 2012, value: '22' },
      { measure_id: measures['Number of arrests for minors in possession - 18 to 20'], year: 2008, value: '177' },
      { measure_id: measures['Number of arrests for minors in possession - 18 to 20'], year: 2009, value: '136' },
      { measure_id: measures['Number of arrests for minors in possession - 18 to 20'], year: 2010, value: '142' },
      { measure_id: measures['Number of arrests for minors in possession - 18 to 20'], year: 2011, value: '212' },
      { measure_id: measures['Number of arrests for minors in possession - 18 to 20'], year: 2012, value: '113' },
      { measure_id: measures['Number of RBS trainings'], year: 2010, value: '39' },
      { measure_id: measures['Number of people trained in RBS'], year: 2008, value: '248' },
      { measure_id: measures['Number of people trained in RBS'], year: 2009, value: '344' },
      { measure_id: measures['Number of people trained in RBS'], year: 2010, value: '1053' },
      { measure_id: measures['Number of people trained in RBS'], year: 2011, value: '1866' },
      { measure_id: measures['Number of people trained in RBS'], year: 2012, value: '909' },
      { measure_id: measures['Number of people trained in RBS'], year: 2013, value: '172' },
      { measure_id: measures['School suspensions due to drugs - ISS'], year: 2008, value: '4' },
      { measure_id: measures['School suspensions due to drugs - ISS'], year: 2009, value: '2' },
      { measure_id: measures['School suspensions due to drugs - ISS'], year: 2010, value: '0' },
      { measure_id: measures['School suspensions due to drugs - ISS'], year: 2011, value: '4' },
      { measure_id: measures['School suspensions due to drugs - ISS'], year: 2012, value: '1' },
      { measure_id: measures['School suspensions due to drugs - ISS'], year: 2013, value: '2' },
      { measure_id: measures['School suspensions due to drugs - OSS'], year: 2008, value: '56' },
      { measure_id: measures['School suspensions due to drugs - OSS'], year: 2009, value: '33' },
      { measure_id: measures['School suspensions due to drugs - OSS'], year: 2010, value: '26' },
      { measure_id: measures['School suspensions due to drugs - OSS'], year: 2011, value: '21' },
      { measure_id: measures['School suspensions due to drugs - OSS'], year: 2012, value: '55' },
      { measure_id: measures['School suspensions due to drugs - OSS'], year: 2013, value: '30' },
      { measure_id: measures['Number of media impressions in radio'], year: 2010, value: '366500' },
      { measure_id: measures['Number of media impressions in Newspress'], year: 2010, value: '37526' },
      { measure_id: measures['Number of media impressions in billboards'], year: 2010, value: '3886632' },
      { measure_id: measures['Number of community changes'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes'], year: 2007, value: '1' },
      { measure_id: measures['Number of community changes'], year: 2008, value: '5' },
      { measure_id: measures['Number of community changes'], year: 2009, value: '8' },
      { measure_id: measures['Number of community changes'], year: 2010, value: '1' },
      { measure_id: measures['Number of community changes'], year: 2011, value: '1' },
      { measure_id: measures['Number of community changes by sector - Business'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Business'], year: 2007, value: '1' },
      { measure_id: measures['Number of community changes by sector - Business'], year: 2008, value: '1' },
      { measure_id: measures['Number of community changes by sector - Business'], year: 2009, value: '2' },
      { measure_id: measures['Number of community changes by sector - Business'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Business'], year: 2011, value: '0' },
      { measure_id: measures['Number of community changes by sector - Education'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Education'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - Education'], year: 2008, value: '0' },
      { measure_id: measures['Number of community changes by sector - Education'], year: 2009, value: '0' },
      { measure_id: measures['Number of community changes by sector - Education'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Education'], year: 2011, value: '0' },
      { measure_id: measures['Number of community changes by sector - Government'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Government'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - Government'], year: 2008, value: '1' },
      { measure_id: measures['Number of community changes by sector - Government'], year: 2009, value: '4' },
      { measure_id: measures['Number of community changes by sector - Government'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Government'], year: 2011, value: '1' },
      { measure_id: measures['Number of community changes by sector - Health Care'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Health Care'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - Health Care'], year: 2008, value: '0' },
      { measure_id: measures['Number of community changes by sector - Health Care'], year: 2009, value: '0' },
      { measure_id: measures['Number of community changes by sector - Health Care'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Health Care'], year: 2011, value: '0' },
      { measure_id: measures['Number of community changes by sector - Law Enforcement'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Law Enforcement'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - Law Enforcement'], year: 2008, value: '1' },
      { measure_id: measures['Number of community changes by sector - Law Enforcement'], year: 2009, value: '2' },
      { measure_id: measures['Number of community changes by sector - Law Enforcement'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Law Enforcement'], year: 2011, value: '0' },
      { measure_id: measures['Number of community changes by sector - Media'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Media'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - Media'], year: 2008, value: '0' },
      { measure_id: measures['Number of community changes by sector - Media'], year: 2009, value: '0' },
      { measure_id: measures['Number of community changes by sector - Media'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Media'], year: 2011, value: '0' },
      { measure_id: measures['Number of community changes by sector - Parents/Caregivers'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Parents/Caregivers'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - Parents/Caregivers'], year: 2008, value: '0' },
      { measure_id: measures['Number of community changes by sector - Parents/Caregivers'], year: 2009, value: '0' },
      { measure_id: measures['Number of community changes by sector - Parents/Caregivers'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Parents/Caregivers'], year: 2011, value: '0' },
      { measure_id: measures['Number of community changes by sector - Faith'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Faith'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - Faith'], year: 2008, value: '0' },
      { measure_id: measures['Number of community changes by sector - Faith'], year: 2009, value: '0' },
      { measure_id: measures['Number of community changes by sector - Faith'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Faith'], year: 2011, value: '0' },
      { measure_id: measures['Number of community changes by sector - Volunteer/Civic Groups'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Volunteer/Civic Groups'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - Volunteer/Civic Groups'], year: 2008, value: '0' },
      { measure_id: measures['Number of community changes by sector - Volunteer/Civic Groups'], year: 2009, value: '0' },
      { measure_id: measures['Number of community changes by sector - Volunteer/Civic Groups'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Volunteer/Civic Groups'], year: 2011, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth'], year: 2008, value: '1' },
      { measure_id: measures['Number of community changes by sector - Youth'], year: 2009, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth'], year: 2011, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth Serving Agencies'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth Serving Agencies'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth Serving Agencies'], year: 2008, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth Serving Agencies'], year: 2009, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth Serving Agencies'], year: 2010, value: '0' },
      { measure_id: measures['Number of community changes by sector - Youth Serving Agencies'], year: 2011, value: '0' },
      { measure_id: measures['Number of community changes by sector - General Community'], year: 2006, value: '0' },
      { measure_id: measures['Number of community changes by sector - General Community'], year: 2007, value: '0' },
      { measure_id: measures['Number of community changes by sector - General Community'], year: 2008, value: '1' },
      { measure_id: measures['Number of community changes by sector - General Community'], year: 2009, value: '0' },
      { measure_id: measures['Number of community changes by sector - General Community'], year: 2010, value: '1' },
      { measure_id: measures['Number of community changes by sector - General Community'], year: 2011, value: '0' },
      { measure_id: measures['Pounds of RX take backs'], year: 2010, value: '229' },
      { measure_id: measures['Pounds of RX take backs'], year: 2011, value: '314' },
      { measure_id: measures['Pounds of RX take backs'], year: 2013, value: '776' },
      { measure_id: measures['Number of new policies approved'], year: 2006, value: '0' },
      { measure_id: measures['Number of new policies approved'], year: 2007, value: '0' },
      { measure_id: measures['Number of new policies approved'], year: 2008, value: '1' },
      { measure_id: measures['Number of new policies approved'], year: 2009, value: '5' },
      { measure_id: measures['Number of new policies approved'], year: 2010, value: '0' },
      { measure_id: measures['Number of new policies approved'], year: 2011, value: '1' }
    ]
  end

  def down
    drop_table :measurements
  end
end
